### ISSUE TITLE
Add task files in packages

### ISSUE THREAD

**Issue by tredoe** [owenthereal/gotask#1]
When it is used a task into a package, the functions exported (like "TaskSomething") of that file are compiled too in the package.

Any way to solve it without to add the task files into a sub-directory?

Related to https://groups.google.com/forum/#!topic/golang-nuts/e8uA_iYHGhs

**Comment by owenthereal** [comment]
@kless Go compiler actually shouldn't compile the tasks into the final binary unless somewhere in your code is calling the task functions. I was told the Go linker would be able to do optimization like this. But I also replied on the Google post to clarify.

**Comment by tredoe** [comment]
I'm using "godoc -http=:6060" in the directory of my package, and godoc is showing the comment of my task: `func TaskBuildData(*task.T)`

Really, it shows all variables and functions exported from the task file.

**Comment by owenthereal** [comment]
`godoc` actually hards code to [exclude `_test.go`](http://golang.org/src/cmd/godoc/dirtrees.go#L41) that's why tests are excluded. I'm not sure there's a way to ignore doc for a public function. But your tasks shouldn't be compiled into the final binary

**Comment by owenthereal** [comment]
@kless I've implemented build tag in gotask (https://github.com/jingweno/gotask/commit/1dc230493977984e9353f61d5ebf535456aab25a) which will exclude tasks in application build. Upgrade gotask and try putting the build tag on top of your task file:

``` go
// +build gotask

package main
...
```

Note that there's an empty line before package definition. Let me know if it doesn't work

**Comment by tredoe** [comment]
It works. Thanks!
