### ISSUE TITLE
Can't run tasks

### ISSUE THREAD

**Issue by Blogoslov** [owenthereal/gotask#20]
Hello,
when I attempt to run example from readme file I received following messages:

./bin/gotask say-hello
can't load package: import cycle not allowed
package .
        imports .
import cycle not allowed
package .
        imports .

I'm using GO version 1.4

**Comment by Blogoslov** [comment]
I think that this can be closed. This item 100 times was discussed.. sorry.

**Comment by owenthereal** [comment]
No worries. Yes, this is because your program has cycle dependencies, which is not allowed in Go.
