### ISSUE TITLE
Name of task binaries

### ISSUE THREAD

**Issue by tredoe** [owenthereal/gotask#4]
"gotask -c" compiles to 'package_name.task' but it would be better if were used the file name since that you could have several task files in the same directory.

e.g. for a file name 'testdata_task.go', the task binary would be 'testdata.task'

**Comment by owenthereal** [comment]
You may have multiple task files in a folder though. So naming to a particular file doesn't work well. I'm planning to let the user to specify name of the build binary. Say:

``` plain
$ gotask -c NAME.task
```

**Comment by owenthereal** [comment]
I'm closing this one. Please reopen if it's still an issue for you
